# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0c8d23eacd7c784427eb4b9a1a1e15ece11462cb117e0be24c976c1af1ec5661dc8a950fab44a5e7263474f7130febc9dfb01391446fb4790d75d2ab044aa5

test:
  secret_key_base: c20e338d7a56a98260d1712172d8f23581e76116ac520d317e0af86090cbd9d8c4f0862d37fa32306e306b1403dfa16f01cb0e6f423c40b62b6c9088c4c4f40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
